; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "SiteForge"
#define MyAppVersion "1.0"
#define MyAppPublisher "Ewan C & Nathan B-M"
#define MyAppURL "https://github.com/Ewan-PHS/SiteForge"
#define MyAppExeName "SIP_Project.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{018476CE-BFCE-4E3E-A226-2221716B39DA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=lowest
;PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer
OutputBaseFilename=SiteForge Installer
SetupIconFile=C:\Not_Onedrive\GitHub\SIP-Project-2026\Design\SiteForge_Logo_V4-4.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{app}\bin"; Flags: uninsalwaysuninstall
Name: "{app}\bin\python"; Flags: uninsalwaysuninstall
Name: "{app}\bin\slic3r"; Flags: uninsalwaysuninstall
Name: "{localappdata}\SiteForge\config";
Name: "{localappdata}\SiteForge\logs";

[Files]
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Delphi\Win64\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Python\dist\V3\*"; DestDir: "{app}\bin\python"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer\vc_redist.x64.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer\Slic3r-1.3.0.64bit\*"; DestDir: "{app}\bin\slic3r"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer\slicerConfig.ini"; DestDir: "{localappdata}\SiteForge\config"; Flags: ignoreversion 
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\bin\vc_redist.x64.exe"; Description: "{cm:LaunchProgram,{#StringChange('Install Visual C++ Redistributable', '&', '&&')}}"; Flags: postinstall
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


