; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "SiteForge"
#define MyAppVersion "1.0"
#define MyAppPublisher "Ewan C & Nathan B-M"
#define MyAppURL "https://github.com/Ewan-PHS/SiteForge"
#define MyAppExeName "SIP_Project.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{018476CE-BFCE-4E3E-A226-2221716B39DA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer
OutputBaseFilename=SiteForge Installer
SetupIconFile=C:\Not_Onedrive\GitHub\SIP-Project-2026\Design\SiteForge_Logo_V4-4.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{app}\bin"; Flags: uninsalwaysuninstall

[Files]
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Delphi\Win64\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Python\requirements.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Python\V3.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer\Install_Requirements.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Not_Onedrive\GitHub\SIP-Project-2026\Installer\python-3.12.3-amd64_Installer.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\python-3.12.3-amd64_Installer.exe"; Parameters: " /quiet InstallAllUsers=1 PrependPath=1 Include_test=0"; Flags: postinstall hidewizard 

Filename: "cmd.exe"; Parameters: "/K ""{app}\Install_Requirements.bat"" ""{app}"""; Flags: postinstall hidewizard

Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


